# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    language: system

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
  - id: terraform-docs-go
    args: ["markdown", "table", "--output-file", "README.md", "./modules"]
